services:
  db:
    image: postgres:15
    container_name: job_match_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=job_match_db
    ports:
      - "5432:5432"